import type { AttendanceRow } from "./types";

export const DEFAULT_ATTENDANCE_DATE = "2024-07-01";

export const INITIAL_ROWS: AttendanceRow[] = [
  {
    id: "emp049",
    name: "Olivia Clark",
    employeeId: "EMP049",
    initials: "OC",
    avatarClass: "bg-teal-100 text-teal-800",
    shiftId: "day-6am-6pm",
    clockIn: "05:50",
    clockOut: "17:56",
    clockInRegularized: false,
    clockOutRegularized: false,
    overtime: null,
    history: [],
  },
  {
    id: "emp012",
    name: "Oscar Romano",
    employeeId: "EMP012",
    initials: "OR",
    avatarClass: "bg-sky-100 text-sky-800",
    shiftId: "day-6am-6pm",
    clockIn: "05:50",
    clockOut: "17:56",
    clockInRegularized: false,
    clockOutRegularized: false,
    overtime: null,
    history: [],
  },
  {
    id: "emp031",
    name: "Arthur Jackson",
    employeeId: "EMP031",
    initials: "AJ",
    avatarClass: "bg-emerald-100 text-emerald-800",
    shiftId: "day-6am-6pm",
    clockIn: "05:51",
    clockOut: "18:12",
    clockInRegularized: false,
    clockOutRegularized: true,
    overtime: null,
    history: [
      {
        id: "h-aj-1",
        savedAt: "2024-07-01T10:14:00.000Z",
        clockInFrom: "05:51",
        clockInTo: "05:51",
        clockOutFrom: "17:40",
        clockOutTo: "18:12",
        shiftFrom: "day-6am-6pm",
        shiftTo: "day-6am-6pm",
      },
    ],
  },
  {
    id: "emp018",
    name: "Evie Carter",
    employeeId: "EMP018",
    initials: "EC",
    avatarClass: "bg-violet-100 text-violet-800",
    shiftId: "day-6am-6pm",
    clockIn: "05:50",
    clockOut: "19:04",
    clockInRegularized: false,
    clockOutRegularized: false,
    overtime: null,
    history: [],
  },
  {
    id: "emp027",
    name: "Ruby Rossi",
    employeeId: "EMP027",
    initials: "RR",
    avatarClass: "bg-amber-100 text-amber-800",
    shiftId: "day-6am-6pm",
    clockIn: "05:51",
    clockOut: "20:22",
    clockInRegularized: false,
    clockOutRegularized: false,
    overtime: null,
    history: [],
  },
  {
    id: "emp041",
    name: "Evie Adams",
    employeeId: "EMP041",
    initials: "EA",
    avatarClass: "bg-rose-100 text-rose-800",
    shiftId: "night-6pm-6am",
    clockIn: "05:50",
    clockOut: "18:08",
    clockInRegularized: true,
    clockOutRegularized: true,
    overtime: null,
    history: [
      {
        id: "h-ea-1",
        savedAt: "2024-07-01T09:02:00.000Z",
        clockInFrom: null,
        clockInTo: "05:50",
        clockOutFrom: null,
        clockOutTo: "18:08",
        shiftFrom: null,
        shiftTo: "night-6pm-6am",
      },
    ],
  },
  {
    id: "emp055",
    name: "Noah Bennett",
    employeeId: "EMP055",
    initials: "NB",
    avatarClass: "bg-slate-100 text-slate-700",
    shiftId: null,
    clockIn: null,
    clockOut: null,
    clockInRegularized: false,
    clockOutRegularized: false,
    overtime: null,
    history: [],
  },
];
