import type { TestSuite } from "@/lib/types";
import { groupRowsIntoScenarios } from "./groupScenarios";

const SAMPLE_ROWS = [
  {
    scenarioId: "S-01",
    scenarioName: "Happy path expense submission",
    stepNo: 1,
    actor: "USER",
    inputType: "text",
    message: "expense",
    expectedResponse: '{"trigger":"expense"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 2,
  },
  {
    scenarioId: "S-01",
    scenarioName: "Happy path expense submission",
    stepNo: 2,
    actor: "SYSTEM",
    inputType: "text",
    message: "Ask for merchant, amount, and date",
    expectedResponse:
      '{"prompt":"Please share merchant, amount, and date for this expense."}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 3,
  },
  {
    scenarioId: "S-01",
    scenarioName: "Happy path expense submission",
    stepNo: 3,
    actor: "USER",
    inputType: "text",
    message: "Starbucks $12.40 on 12 Aug",
    expectedResponse: '{"merchant":"Starbucks","amount":12.4,"currency":"USD","date":"2026-08-12"}',
    testData: '{"merchant":"Starbucks","amount":12.40}',
    endOfScenarioRaw: "",
    rowNumber: 4,
  },
  {
    scenarioId: "S-01",
    scenarioName: "Happy path expense submission",
    stepNo: 4,
    actor: "SYSTEM",
    inputType: "text",
    message: "Confirm draft expense",
    expectedResponse: '{"status":"draft","policy":"within_limit"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 5,
  },
  {
    scenarioId: "S-01",
    scenarioName: "Happy path expense submission",
    stepNo: 5,
    actor: "USER",
    inputType: "action",
    message: "submit",
    expectedResponse: '{"action":"submit"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 6,
  },
  {
    scenarioId: "S-01",
    scenarioName: "Happy path expense submission",
    stepNo: 6,
    actor: "MANAGER",
    inputType: "action",
    message: "approve",
    expectedResponse: '{"decision":"approved"}',
    testData: '{"approver":"mgr-204"}',
    endOfScenarioRaw: "",
    rowNumber: 7,
  },
  {
    scenarioId: "S-01",
    scenarioName: "Happy path expense submission",
    stepNo: 7,
    actor: "SYSTEM",
    inputType: "text",
    message: "Finalize expense",
    expectedResponse: '{"status":"posted","id":"EXP-1001"}',
    testData: "",
    endOfScenarioRaw: "YES",
    rowNumber: 8,
  },
  {
    scenarioId: "S-02",
    scenarioName: "OCR transposes digits in the amount",
    stepNo: 1,
    actor: "USER",
    inputType: "text",
    message: "expense",
    expectedResponse: '{"trigger":"expense"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 9,
  },
  {
    scenarioId: "S-02",
    scenarioName: "OCR transposes digits in the amount",
    stepNo: 2,
    actor: "USER",
    inputType: "image",
    message: "Upload receipt",
    expectedResponse: '{"ocr_status":"parsed"}',
    testData: '{"receipt":"receipt_s02.jpg"}',
    endOfScenarioRaw: "",
    rowNumber: 10,
  },
  {
    scenarioId: "S-02",
    scenarioName: "OCR transposes digits in the amount",
    stepNo: 3,
    actor: "SYSTEM",
    inputType: "text",
    message: "Extract amount from receipt",
    expectedResponse: '{"amount":84.5,"currency":"USD","confidence":0.81}',
    testData: '{"true_amount":48.5}',
    endOfScenarioRaw: "",
    rowNumber: 11,
  },
  {
    scenarioId: "S-02",
    scenarioName: "OCR transposes digits in the amount",
    stepNo: 4,
    actor: "USER",
    inputType: "text",
    message: "The amount should be 48.50 not 84.50",
    expectedResponse: '{"correction":"accepted","amount":48.5}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 12,
  },
  {
    scenarioId: "S-02",
    scenarioName: "OCR transposes digits in the amount",
    stepNo: 5,
    actor: "SYSTEM",
    inputType: "text",
    message: "Confirm corrected amount",
    expectedResponse: '{"status":"draft","amount":48.5,"ocr_override":true}',
    testData: "",
    endOfScenarioRaw: "YES",
    rowNumber: 13,
  },
  {
    scenarioId: "S-03",
    scenarioName: "Manager rejects over-policy amount",
    stepNo: 1,
    actor: "USER",
    inputType: "text",
    message: "expense",
    expectedResponse: '{"trigger":"expense"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 14,
  },
  {
    scenarioId: "S-03",
    scenarioName: "Manager rejects over-policy amount",
    stepNo: 2,
    actor: "USER",
    inputType: "text",
    message: "Client dinner $420 at The Oak Room",
    expectedResponse: '{"merchant":"The Oak Room","amount":420,"policy_flag":"over_limit"}',
    testData: '{"policy_limit":150}',
    endOfScenarioRaw: "",
    rowNumber: 15,
  },
  {
    scenarioId: "S-03",
    scenarioName: "Manager rejects over-policy amount",
    stepNo: 3,
    actor: "SYSTEM",
    inputType: "text",
    message: "Route to manager with policy warning",
    expectedResponse: '{"routing":"manager","reason":"over_limit"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 16,
  },
  {
    scenarioId: "S-03",
    scenarioName: "Manager rejects over-policy amount",
    stepNo: 4,
    actor: "MANAGER",
    inputType: "action",
    message: "reject",
    expectedResponse: '{"decision":"rejected","reason":"exceeds_meal_policy"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 17,
  },
  {
    scenarioId: "S-03",
    scenarioName: "Manager rejects over-policy amount",
    stepNo: 5,
    actor: "SYSTEM",
    inputType: "text",
    message: "Notify employee of rejection",
    expectedResponse: '{"status":"rejected","notify":"employee"}',
    testData: "",
    endOfScenarioRaw: "YES",
    rowNumber: 18,
  },
  {
    scenarioId: "S-04",
    scenarioName: "Missing receipt follow-up",
    stepNo: 1,
    actor: "USER",
    inputType: "text",
    message: "expense",
    expectedResponse: '{"trigger":"expense"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 19,
  },
  {
    scenarioId: "S-04",
    scenarioName: "Missing receipt follow-up",
    stepNo: 2,
    actor: "USER",
    inputType: "text",
    message: "Uber $28.10 yesterday, no receipt yet",
    expectedResponse: '{"merchant":"Uber","amount":28.1,"receipt":"missing"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 20,
  },
  {
    scenarioId: "S-04",
    scenarioName: "Missing receipt follow-up",
    stepNo: 3,
    actor: "SYSTEM",
    inputType: "text",
    message: "Request receipt before submit",
    expectedResponse: '{"blocker":"receipt_required"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 21,
  },
  {
    scenarioId: "S-04",
    scenarioName: "Missing receipt follow-up",
    stepNo: 4,
    actor: "USER",
    inputType: "file",
    message: "Attach receipt later",
    expectedResponse: '{"receipt":"attached"}',
    testData: '{"file":"uber_receipt.pdf"}',
    endOfScenarioRaw: "",
    rowNumber: 22,
  },
  {
    scenarioId: "S-04",
    scenarioName: "Missing receipt follow-up",
    stepNo: 5,
    actor: "SYSTEM",
    inputType: "text",
    message: "Clear receipt blocker",
    expectedResponse: '{"status":"draft","receipt":"present"}',
    testData: "",
    endOfScenarioRaw: "YES",
    rowNumber: 23,
  },
  {
    scenarioId: "S-05",
    scenarioName: "Multi-currency conversion",
    stepNo: 1,
    actor: "USER",
    inputType: "text",
    message: "expense",
    expectedResponse: '{"trigger":"expense"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 24,
  },
  {
    scenarioId: "S-05",
    scenarioName: "Multi-currency conversion",
    stepNo: 2,
    actor: "USER",
    inputType: "text",
    message: "Hotel in London £240 on 3 Aug",
    expectedResponse: '{"merchant":"Hotel","amount":240,"currency":"GBP","date":"2026-08-03"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 25,
  },
  {
    scenarioId: "S-05",
    scenarioName: "Multi-currency conversion",
    stepNo: 3,
    actor: "SYSTEM",
    inputType: "text",
    message: "Convert to company currency USD",
    expectedResponse: '{"amount_usd":307.2,"fx_rate":1.28}',
    testData: '{"base_currency":"USD"}',
    endOfScenarioRaw: "",
    rowNumber: 26,
  },
  {
    scenarioId: "S-05",
    scenarioName: "Multi-currency conversion",
    stepNo: 4,
    actor: "SYSTEM",
    inputType: "text",
    message: "Present converted draft",
    expectedResponse: '{"status":"draft","amount":240,"currency":"GBP","amount_home":307.2}',
    testData: "",
    endOfScenarioRaw: "YES",
    rowNumber: 27,
  },
  {
    scenarioId: "S-06",
    scenarioName: "Duplicate expense detection",
    stepNo: 1,
    actor: "USER",
    inputType: "text",
    message: "expense",
    expectedResponse: '{"trigger":"expense"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 28,
  },
  {
    scenarioId: "S-06",
    scenarioName: "Duplicate expense detection",
    stepNo: 2,
    actor: "USER",
    inputType: "text",
    message: "Starbucks $12.40 on 12 Aug",
    expectedResponse: '{"merchant":"Starbucks","amount":12.4,"date":"2026-08-12"}',
    testData: '{"existing_id":"EXP-1001"}',
    endOfScenarioRaw: "",
    rowNumber: 29,
  },
  {
    scenarioId: "S-06",
    scenarioName: "Duplicate expense detection",
    stepNo: 3,
    actor: "SYSTEM",
    inputType: "text",
    message: "Flag likely duplicate",
    expectedResponse: '{"duplicate":true,"match_id":"EXP-1001","confidence":0.93}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 30,
  },
  {
    scenarioId: "S-06",
    scenarioName: "Duplicate expense detection",
    stepNo: 4,
    actor: "USER",
    inputType: "action",
    message: "discard",
    expectedResponse: '{"action":"discard"}',
    testData: "",
    endOfScenarioRaw: "",
    rowNumber: 31,
  },
  {
    scenarioId: "S-06",
    scenarioName: "Duplicate expense detection",
    stepNo: 5,
    actor: "SYSTEM",
    inputType: "text",
    message: "Close without posting",
    expectedResponse: '{"status":"discarded","reason":"duplicate"}',
    testData: "",
    endOfScenarioRaw: "YES",
    rowNumber: 32,
  },
];

export function loadSampleSuite(): TestSuite {
  const grouped = groupRowsIntoScenarios(SAMPLE_ROWS);
  return {
    scenarios: grouped.scenarios,
    issues: grouped.issues,
    sourceName: "sample-expense-agent-suite.xlsx",
    rawRowCount: SAMPLE_ROWS.length,
  };
}

export const SAMPLE_SUITE_DESCRIPTION =
  "Demo suite for an expense-agent workflow. Six scenarios cover happy path, OCR digit transposition, manager rejection, missing receipt, FX conversion, and duplicate detection.";
